### ISSUE TITLE
Usage without Google Auth

### ISSUE THREAD

**Issue by Haze-sh** [lukesmurray/reschedule#10]
I would like to use this project but without being forced to use google calendar, is that possible by fixing #4?

I would rather reschedule to an .ics file which can bee used on most services or offline calendars.

Also right now it's not possible to parse tasks without a unique id, maybe that can change by generating the id inside reschedule?

**Comment by lukesmurray** [comment]
Couple of issues here

- the unique id has to be defined in the file in order to link the task to the event in the calendar. The only other way to compute unique ids would be based on file structure (i.e. line number) or todo content (text) both of which can change. If the id is lost then we could leave dangling events in your calendar which would be a bad user experience.
- unfortunately the scheduling implementation relies on google api endpoints such as *free_busy* which would need to be implemented on top of ics for integration with ics. You can see some examples in the calendar_api file https://github.com/lukesmurray/reschedule/blob/master/reschedule/calendar_api.py. Because the current code is tightly coupled to google I don't think removing auth alone would solve your issue.

At the moment I don't have much time to improve this project. It was a weekend experiment and I don't plan to make it more general. However you can fork the project if you would like. I will add an MIT license so you can do whatever you want with the existing code.

**Comment by lukesmurray** [comment]
Also feel free to provide a pull request with integration to ICS. I would be happy to review it although I cannot promise it would be merged. I hope that answers your question! I apologize for not having the time to make the changes you want at the moment!
